-- Executar os comandos abaixo logado com um usuário com permissão para criar database e usuários

CREATE ROLE erp LOGIN
    ENCRYPTED PASSWORD 'md518bece2cf526c5de3e3208516719fa29'
    SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE ROLE rpdv LOGIN
    ENCRYPTED PASSWORD 'md5336b5a9e57865b05f53d4f6fcb21959f'
    SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE ROLE ntpaulista LOGIN
    ENCRYPTED PASSWORD 'md5f42471fc3f43b6217dac7999ab9d4d0b'
    SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

-- Criação do database erp (flexdb)
CREATE DATABASE erp OWNER erp TEMPLATE template0 ENCODING latin1 LC_COLLATE 'C' LC_CTYPE 'C';

-- Criação do database wrpdv
CREATE DATABASE wrpdv OWNER rpdv TEMPLATE template0 ENCODING latin1 LC_COLLATE 'C' LC_CTYPE 'C';
